### ISSUE TITLE
Observation/no ussue: LEDs

### ISSUE THREAD

**Issue by UweBonnes** [rkollataj/mcba_usb#3]
Hello,

thanks for your work! I just received my part, compiled and installed the driver and can read and send CAN  commands.
However the CANERR LED is constant green and neither CANRX nor CAN TX  flash with messages sent or received. Is there some error in my setup?

Otherwise the blue USB Power LED is blindingly bright. What did the designer smoke :-)

**Comment by UweBonnes** [comment]
Okay, installed the windows software in Virtualbox and the LED behaviour is the same: ERR constant on, RX/TX never visible...

**Comment by rkollataj** [comment]
I'm glad it works for you :) All (most of) leds are controlled via firmware. CANERR LED is constant green when there is no error on the line. Otherwise it changes to red. There is no influence on CANTX and CANRX leds as they are connected directly to CANTX and CANRX lines from MCU. If you are using high CAN speeds you may not spot that they are blinking. If you decrease the speed blinking becomes visible.

**Comment by whiteox** [comment]
I am not as successful at compiling the driver.
I think i am missing some dependencies or something...
running ubuntu linux 14.04 (vanilla)
these are the last of the make command.
...help..


/home/btumbri/software_compile/PIC_CAN_ANALISER/mcba_usb/mcba_usb.c:1210:16: error: expected declaration specifiers or ‘...’ before string constant
 MODULE_LICENSE("GPL v2");
                ^
/home/btumbri/software_compile/PIC_CAN_ANALISER/mcba_usb/mcba_usb.c: In function ‘mcba_usb_xmit’:
/home/btumbri/software_compile/PIC_CAN_ANALISER/mcba_usb/mcba_usb.c:965:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
cc1: some warnings being treated as errors
make[2]: *** [/home/btumbri/software_compile/PIC_CAN_ANALISER/mcba_usb/mcba_usb.o] Error 1
make[1]: *** [_module_/home/btumbri/software_compile/PIC_CAN_ANALISER/mcba_usb] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.19.0-69-generic'
make: *** [all] Error 2
btumbri@Compaq:~/software_compile/PIC_CAN_ANALISER/mcba_usb$

**Comment by rkollataj** [comment]
I've never tried to compile against 3.19 kernel. I'll try to do this
tomorrow. The error and warning looks strange though...

2016-12-19 14:04 GMT+01:00 whiteox <notifications@github.com>:

**Comment by rkollataj** [comment]
@whiteox 
It seems that 3.19 kernel has different header include structure. I've added additional headers that fixes the problem. Fix is on the master branch. For the future: in case of other issues please open new ticket.

**Comment by whiteox** [comment]
Thanx
