### ISSUE TITLE
multiple adapters

### ISSUE THREAD

**Issue by nivoset** [rkollataj/mcba_usb#6]
has anyone hooked up multiple of these to the same computer? are there any issues? also, anything for enumeration of them?

**Comment by rkollataj** [comment]
The driver supports multiple adapters simultaneously. As it is a socketcan driver every connected device can be enumerated and configured via iproute2 (i.e. ip link). I recommend you to use 4.12 kernel as the driver is integrated with it.

**Comment by nivoset** [comment]
ok thanks, i haven't gotten a second unit yet so it wasn't possible for me to verify, im getting one in a few days, time to look for my programmer
